### ISSUE TITLE
Make this provider Terraform 0.12 ready

### ISSUE THREAD

**Issue by antonbabenko** [callensm/terraform-provider-dropbox#6]
Thank you for this provider!

**Is your feature request related to a problem? Please describe.**
I'd like to use this provider to manage files (https://github.com/antonbabenko/terraform-docs-as-pdf/issues/2) on Dropbox using Terraform 0.12, but it is not compatible with available 0.12 beta or alpha.

**Describe the solution you'd like**
Recompile it with Terraform 0.12 source code

**Describe alternatives you've considered**
Terraform 0.11 potentially will work fine with this provider (see #7), but I would like to use Terraform 0.12 there

**Additional context**
```
provider "dropbox" {
  access_token = "${var.token}"
}

data "dropbox_user_current" "curr" {}

output "user_id" {
  value = "${data.dropbox_user_current.curr.account_id}"
}
```

Gives this error:
```
Error: Failed to retrieve schema from provider "dropbox": rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
```

**Comment by callensm** [comment]
The TLS error could be something on your end. Are you working behind a proxy or something that would cause handshake failure if not done properly?

**Comment by antonbabenko** [comment]
I don’t think there is anything wrong on my side, because I used Terraform normally right after I was trying this provider and opened this issue yesterday.

24 лют. 2019 р. о 16:11 Matthew Callens <notifications@github.com> пише:

**Comment by callensm** [comment]
According to [this document](https://www.terraform.io/upgrade-guides/0-12.html) Terraform's 0.12 has a redesigned RPC system that seems to not be cross-compatible with previous version of Terraform.

I'm going to wait until it is actually released before I update the provider to use 0.12.

**Comment by callensm** [comment]
Supports terraform 0.12 as of v3 release

**Comment by antonbabenko** [comment]
Great! Thank you!
